language: go
go:
  - "1.12.x"
os:
  - linux
  - osx
  - windows

git:
  depth: 1

env:
  - GO111MODULE=on CGO_ENABLED=1
  - GO111MODULE=on CGO_ENABLED=0

install: true

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
